<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AutoMapper" Version="16.1.1" />
        <PackageReference Include="Azure.Storage.Blobs" Version="12.27.0" />
        <PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
        <PackageReference Include="MailKit" Version="4.16.0" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.7" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.7">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.7" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
        <PackageReference Include="Stripe.net" Version="51.1.0" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.1" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Controllers\" />
      <Folder Include="Entities\" />
      <Folder Include="Helpers\" />
      <Folder Include="InfoFiles\" />
      <Folder Include="Models\Dtos\" />
      <Folder Include="Repositories\" />
      <Folder Include="Services\" />
    </ItemGroup>

</Project>
